# -*- coding: utf-8 -*-
"""Project SentimentAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w_nP5BcrdywcPN0nKHAz7D0DaJAZPG2n
"""

acc = accuracy_score(y_test, y_pred) * 100
print(f"Test Accuracy: {acc:.2f}%")
total_samples = len(df)
train_samples = len(X_train)
test_samples = len(X_test)

print("Train-Test Split Information")
print("-----------------------------")
print(f"Total Samples : {total_samples}")
print(f"Training Data : {train_samples} ({(train_samples/total_samples)*100:.0f}%)")
print(f"Testing Data  : {test_samples} ({(test_samples/total_samples)*100:.0f}%)")

acc = accuracy_score(y_test, y_pred) * 100
print(f"Test Accuracy: {acc:.2f}%")
total_samples = len(df)
train_samples = len(X_train)
test_samples = len(X_test)

print("Train-Test Split Information")
print("-----------------------------")
print(f"Total Samples : {total_samples}")
print(f"Training Data : {train_samples} ({(train_samples/total_samples)*100:.0f}%)")
print(f"Testing Data  : {test_samples} ({(test_samples/total_samples)*100:.0f}%)")

def predict_sentiment(text):
    seq = tokenizer.texts_to_sequences([text])
    pad = pad_sequences(seq, maxlen=max_len)
    prediction = model.predict(pad)[0][0]
    return "Positive" if prediction > 0.5 else "Negative"

print(predict_sentiment("This product is amazing and tastes great"))
print(predict_sentiment("Worst product I have ever bought"))

plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.legend()
plt.show()

plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.legend()
plt.show()

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,4))
plt.imshow(cm)
plt.title("Confusion Matrix")
plt.colorbar()
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

y_pred = (model.predict(X_test_pad) > 0.5).astype(int)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

history = model.fit(
    X_train_pad, y_train,
    epochs=5,
    batch_size=64,
    validation_split=0.1
)

model = Sequential([
    Embedding(10000, 128, input_length=max_len),
    LSTM(128),
    Dropout(0.5),
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

tokenizer = Tokenizer(num_words=10000)
tokenizer.fit_on_texts(X_train)

X_train_seq = tokenizer.texts_to_sequences(X_train)
X_test_seq = tokenizer.texts_to_sequences(X_test)

max_len = 200
X_train_pad = pad_sequences(X_train_seq, maxlen=max_len)
X_test_pad = pad_sequences(X_test_seq, maxlen=max_len)

X = df['text']
y = df['sentiment']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

df = df.sample(60000, random_state=42)

# Select required columns
df = df[['Text', 'Score']]

# Remove neutral reviews
df = df[df['Score'] != 3]

# Create sentiment column
df['sentiment'] = df['Score'].apply(lambda x: 1 if x >= 4 else 0)

# Rename column
df.rename(columns={'Text': 'text'}, inplace=True)

# Remove nulls
df.dropna(inplace=True)

df.head()

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/data/amazon_reviews.csv')
df = df[['Text', 'Score']]

import pandas as pd
import numpy as np
import nltk
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout

nltk.download('stopwords')

!pip install nltk tensorflow pandas matplotlib scikit-learn